spring:
  ldap:
    urls: ldap://localhost:389
    base: dc=example,dc=com
    username: cn=admin,dc=example,dc=com
    password: admin
    base-environment-properties:
      java.naming.ldap.attributes.binary: objectGUID 