# WebSocket 配置
websocket:
  # 端点配置
  endpoint: /ws
  # 允许的源
  allowed-origins: "*"
  # 心跳间隔（秒）
  heartbeat-interval: 30
  # 连接超时（秒）
  connection-timeout: 60
  # 最大消息大小（字节）
  max-message-size: 65536
  # 最大连接数
  max-connections: 1000 