# RabbitMQ 配置
spring:
  rabbitmq:
    # RabbitMQ 服务器地址
    host: localhost
    # RabbitMQ 服务器端口
    port: 5672
    # 用户名
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # 连接超时时间（毫秒）
    connection-timeout: 60000
    # 请求心跳超时时间（毫秒）
    requested-heartbeat: 60
    # 自动启动
    listener:
      simple:
        auto-startup: true
        # 并发消费者数量
        concurrency: 1
        # 最大并发消费者数量
        max-concurrency: 10
        # 预取数量
        prefetch: 1
        # 默认重试策略
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0 