# RabbitMQ 默认配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000
    requested-heart-beat: 60
    automatic-recovery-enabled: true
    network-recovery-interval: 5000 