# 日志配置
logging:
  config: classpath:logback-spring.xml
  file:
    path: /data/logs/${spring.application.name}
  level:
    root: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 